export const Login_Api = "http://localhost:3001/api/auth/login"
export const SignUp_Api = "http://localhost:3000/api/user/signup"
export const VerifyOtp_Api = "http://localhost:3000/api/user/verifyOtp"
export const LoginWithGoogle_Api="http://localhost:3000/api/user/loginWithGoogle"
export const AddProfile_Api="http://localhost:3000/api/user/AddProfile"